{% set name = "importlib" %}
{% set version = "1.0.4" %}
{% set checksum = "b6ee7066fea66e35f8d0acee24d98006de1a0a8a94a8ce6efe73a9a23c8d9826" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [py27 or py>30]
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - importlib

about:
  home: https://github.com/brettcannon/importlib
  license: PSF2
  license_family: PSF
  license_file: LICENSE
  summary: Backport of importlib.import_module() from Python 2.7

extra:
  recipe-maintainers:
    - jakirkham
