travis:
  secure:
    BINSTAR_TOKEN: ZNE4kz2n5SCTIX7zw9IZJcbNzwE1WAtGIx1WAivbWnOjkdBoUN+UuxDGrpQsexfjwRQHVPwhHXcy1rUvnhfFVJ4li8HuIWu15ROhDybDg72iTalpZel2C1gliQxFdx1C6p9OdMrd2+2WLIEVTKE6oJKqfKLo7GyDtFt1eYw1EsdfqWhUP0atbNO2DX+oMxS35M1ezfwE7Pj7DenDpWazEx5JcETAhPMv5xyWVJxY5XUhXO7Ymg4Kqrpg4NLci1I7Gb7/0EWh8ZsX1nNQHvG2OAExAatD38DhzvCmCGj0Zbt7skfQYM39JU3QXTYN7eDjEUUWNpSWJtNbo+hXao0MYjxzLOGN7tYisPk4Er8CtJzp5NjRvPbjmdv8BJH8tbkkh1xckmICFw48cj48Lmv5pa99od9j63Qi3kZsoYgpbNiZ+n1Uw4o74swxYpp3GHXpg66oztgQ9+du5GVauuIce5ihSlzgwsR43PtjKjmRdsY5r+TC6KkWvGqtCtalcuO1hv2yUDroqu7w1EYpInZqvPllOCxshIGns+wrQLvse3OsoMOy1HyX/nHVXz5Au26VNf1cbaenruZpSP3h38JNu43edqruPUT2S9UCtD3JT5HIXOpCvwxWDEG05L7h6CUnxMmF/qZYzEgWThjmVBSaM6YfvfcNvc8l1uM68NmFduc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
