travis:
  secure:
    BINSTAR_TOKEN: jVGzobj+P7ZmFazS5opzL5B2maoyPC77dXcEulGc73pW0vKtU0UsCaaZ84yHzvPqY1JwqB+hJgWWz/Ed8aTW2ZPCb9+d7sWoRfKhfKxI4Z6v5A8LlyOxp4AndyH6kfq5gZBPW6wrn4qG5ycrc0IjK+UNypHO6L/bsJAPl+oor+VmD4ndTKI8eLojVCTol8LS+4SYm3jkhcSZ0853pMNjl/3gbg+/4JD1UDyCEyowTCENxKA2YWaoH6b1XJTPyh/I3bl05NxX7twFqGMaZM5SX5xSJEDrUgruGOBdze3q4l37BFoYUz04IEVmmxrxq4xf0SVInJSChee9exPZvLzRwQMgXZIlwI517ExhyJLKoI0lklqIxKFBRIIRoQCmLe+D7ZLMba7fffQa7FS8/b8AmEtr3vyxIiljexWQ+bRAf97Vzhmqb01oO9gDahbJcEsXDAkXXL6jqWlDvq3/p21KMJXIN72xoJkOUnFUUUijbIrAlzkYFwaCzFcgKTH07Qn/UsY7JCbu6denxAUjngQijaenI7IDZ/G7/zSA52xrZrIv6eN9ePH3gHKltKeOdwi8Ew+FopY/e0aLWgh5oHChYmufZGHDiTose8liL4Q2F4T8bA/Esu5Z/XiI7oF0+xgOgXPOAYL9msLN26Ced5xjBWzZ9RQ6SncYhAVxS5ugXDs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
