travis:
  secure:
    BINSTAR_TOKEN: LlrYzVPC6nRbVwj1vyGVVleIxazGtUkMptZYmWXhYQj8/45qPojmQAxuxZhy9TdtsA7+1Bqlsr0qSsPNMKQSykwo3+f37t8K6fxIKl96y6UrqkSyM76oTBdcXWqUzBOVZmlNfedbje9v5q9MgUMG8i8bDMyCjIfs+iciW7yRObftdz9SzTBZg4OxcYEzwLUFNZhwXpy/Gs9quChoxlPPds7gMMRkNrXrdpphEegd+UCHW6/FZ6Hd+eCyCsrqAffgzaJRsEAGklsiITPXv81p/G70UaP85P59Qi7m421/+vk7PfUYGtxccj7yNo15CmU2v6LVEQkmV+hMvDEev8vCAl/JuE1F6nb8yUgOyLR3o3C20dtACukStsU0TI5MLOJNZKrSrwc63+xdunI6rRZfSHMlIT+1M0rY8cBPRaEd1OXUpsY89BIJn5FohNV5k7pxCsRS7KVnF2KNeEgkdIcLRq6eq0A3cNMxIJaEYMlg6OvNWitP1EAJU++oIEr0AvqaXvqqhgZQ0Tf+zj/yStx8V7hJDDxyVxb6veabMLqXHTp/06mUJqECUliC16M6W3AJxLKQDndRBua9bEJUW5NzwUDFuAzUf1ARU3Y88bMV2COamjhbdAb1DQFX5DEGFB7+9giRqLwE1YnO3hcB61a1iOKzmI9cWHWOY6XlYfz3y7M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
